function csv_import = csv_import(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   VID11GT1 = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   VID11GT1 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   vid11gt1 = importfile('vid11_gt.csv', 1, 296);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/06/01 17:28:28

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%s)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: text (%s)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: text (%s)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: text (%s)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%s%f%f%f%f%s%f%f%f%f%s%f%f%f%f%s%f%f%f%f%s%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15,16, 17, 18, 19, 20, 22, 23, 24, 25, 26,27,28,29,30,31]) = cellfun(@(x) num2cell(x), dataArray([2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14, 15,16, 17, 18, 19, 20, 22, 23, 24, 25,26,27,28,29,30,31]), 'UniformOutput', false);
csv_import = [dataArray{1:end-1}];
